apiVersion: projectcalico.org/v3
kind: LicenseKey
metadata:
  creationTimestamp: null
  name: default
spec:
  certificate: |+
    -----BEGIN CERTIFICATE-----
    MIIFxjCCA66gAwIBAgIQVq3rz5D4nQF1fIgMEh71DzANBgkqhkiG9w0BAQsFADCB
    tTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh
    biBGcmFuY2lzY28xFDASBgNVBAoTC1RpZ2VyYSwgSW5jMSIwIAYDVQQLDBlTZWN1
    cml0eSA8c2lydEB0aWdlcmEuaW8+MT8wPQYDVQQDEzZUaWdlcmEgRW50aXRsZW1l
    bnRzIEludGVybWVkaWF0ZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMTgwNDA1
    MjEzMDI5WhcNMjAxMDA2MjEzMDI5WjCBnjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
    CkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xFDASBgNVBAoTC1Rp
    Z2VyYSwgSW5jMSIwIAYDVQQLDBlTZWN1cml0eSA8c2lydEB0aWdlcmEuaW8+MSgw
    JgYDVQQDEx9UaWdlcmEgRW50aXRsZW1lbnRzIENlcnRpZmljYXRlMIIBojANBgkq
    hkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAwg3LkeHTwMi651af/HEXi1tpM4K0LVqb
    5oUxX5b5jjgi+LHMPzMI6oU+NoGPHNqirhAQqK/k7W7r0oaMe1APWzaCAZpHiMxE
    MlsAXmLVUrKg/g+hgrqeije3JDQutnN9h5oZnsg1IneBArnE/AKIHH8XE79yMG49
    LaKpPGhpF8NoG2yoWFp2ekihSohvqKxa3m6pxoBVdwNxN0AfWxb60p2SF0lOi6B3
    hgK6+ILy08ZqXefiUs+GC1Af4qI1jRhPkjv3qv+H1aQVrq6BqKFXwWIlXCXF57CR
    hvUaTOG3fGtlVyiPE4+wi7QDo0cU/+Gx4mNzvmc6lRjz1c5yKxdYvgwXajSBx2pw
    kTP0iJxI64zv7u3BZEEII6ak9mgUU1CeGZ1KR2Xu80JiWHAYNOiUKCBYHNKDCUYl
    RBErYcAWz2mBpkKyP6hbH16GjXHTTdq5xENmRDHabpHw5o+21LkWBY25EaxjwcZa
    Y3qMIOllTZ2iRrXu7fSP6iDjtFCcE2bFAgMBAAGjZzBlMA4GA1UdDwEB/wQEAwIF
    oDATBgNVHSUEDDAKBggrBgEFBQcDAjAdBgNVHQ4EFgQUIY7LzqNTzgyTBE5efHb5
    kZ71BUEwHwYDVR0jBBgwFoAUxZA5kifzo4NniQfGKb+4wruTIFowDQYJKoZIhvcN
    AQELBQADggIBAAK207LaqMrnphF6CFQnkMLbskSpDZsKfqqNB52poRvUrNVUOB1w
    3dSEaBUjhFgUU6yzF+xnuH84XVbjD7qlM3YbdiKvJS9jrm71saCKMNc+b9HSeQAU
    DGY7GPb7Y/LG0GKYawYJcPpvRCNnDLsSVn5N4J1foWAWnxuQ6k57ymWwcddibYHD
    OPakOvO4beAnvax3+K5dqF0bh2Np79YolKdIgUVzf4KSBRN4ZE3AOKlBfiKUvWy6
    nRGvu8O/8VaI0vGaOdXvWA5b61H0o5cm50A88tTm2LHxTXynE3AYriHxsWBbRpoM
    oFnmDaQtGY67S6xGfQbwxrwCFd1l7rGsyBQ17cuusOvMNZEEWraLY/738yWKw3qX
    U7KBxdPWPIPd6iDzVjcZrS8AehUEfNQ5yd26gDgW+rZYJoAFYv0vydMEyoI53xXs
    cpY84qV37ZC8wYicugidg9cFtD+1E0nVgOLXPkHnmc7lIDHFiWQKfOieH+KoVCbb
    zdFu3rhW31ygphRmgszkHwApllCTBBMOqMaBpS8eHCnetOITvyB4Kiu1/nKvVxhY
    exit11KQv8F3kTIUQRm0qw00TSBjuQHKoG83yfimlQ8OazciT+aLpVaY8SOrrNnL
    IJ8dHgTpF9WWHxx04DDzqrT7Xq99F9RzDzM7dSizGxIxonoWcBjiF6n5
    -----END CERTIFICATE-----

  token: eyJhbGciOiJBMTI4R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMTI4R0NNIiwiaXYiOiJHbjdJOWk4RUl2WjN1RzVMIiwidGFnIjoiVWFLQ0xiNlF6NWFmcDlLRVU4WUlpQSIsInR5cCI6IkpXVCJ9.a4Hcnb7wGemNeRHseUC9mw.JgCHZI9tUTE-RcSx.0DWzNYDBVZsDmTIlpTYTqHkhgTiq6ZwknLBalnAiO9ElaFVZUiaTLm7jS5ltz3DECaxqbLFwBEWtckpCEwLJvJEuWHrXNR47KS3W3KEjDiLu6KO-_mByyykN5FhJntm3Yl7ZOLt0bq-qOrYHp9fBPQGMG5WXDBYur8S0KrsHWXwO5jhXrg_g6m_p_-T1pkB4hbOXIkXZCNOJsg1laQY76LGIDR6FkJV5hlCqadYwbVl5M1p9ojC8xXz3k9RlhH_JFlYx1DgxzjeZWuv8DojP-e4qsYnFiegRBSQH3umeyqyf0E8MVVxMrV5Q1NQG096ZE3fmtSVhYWuvFBXf3IKnY1yY5sc3ZJ1mWRldhnsU-B-BGR54cm1FmeVb5kZnctZXKXOvw7OgISY2PR-_h3yqXxGXTRY_-5GDFljt403ks6rmXWcO_pK55p9EYsU0rAS-mIJ18fhfPMHpHZ75W2-EkF5SIg-fnA1Oz6l76aZE0I4obQ4FBvU23QKNFp4_6APY_5LnX9zCD2irI9Z1xY4vJTA4qPt2oyBdAPrXv5lTfutRIEfHMbOd1sM7Xtf7phLWnwPEON3ySys_Y4m1hjrUVso2fcTidCGCLeiP9RwMGq0PQNa_OesFv12xalBJgwOujWMxHb9tinIUz-wRouJL_uQiFcU6_hVValWBYAm_EPQ2-EdHyto6AHnh_3ksn-y7ACfTHNxuR5tINIuTxe1GepAzBzOzAufY11XZzFhDFZAWNTHIEjNMtuuR3Efg4ZUEjZh9tmKsYtD98iGg5b7_0UCSPWtR00e_F8Ix8Ps9H9n5soOUQUCHT6JnV1skmJb3KHmV7U02YNXkWsEcFjVQcOwUtiJdadMBax-EUBVQyP1fsnsdt5oDc1w-jHzU-iqW_oCLZ4qSC3ceQ6DkMMqGjNFkZ2q9mhUz0jjaORJwBmSgRrfS8MQS7QedtZ0hNKH7f74WkfYWicyGE7cH1J_nrtVzeRULIteQdpeVKJ3UkNpUSAl8NPHBCz3SiOkBit1D29UYO-20aopnM3DOuvQUe2-BPkwP4nPKEKJVOIk0j-Hx3LQsslsxuAE0VS5-Z8rlcWYPj1hZXK9jCKc5128Rb0Qz.ZhB0RIHIy--qQWbqSuhxOA
